### ISSUE TITLE
Plans for KC 23.0.0?

### ISSUE THREAD

**Issue by D-Simona-G** [MaikKingma/keycloak-configAsCode-demo#1]
Firstly, you're doing an excellent job with this demo. 

Not really an issue per se, but any hint on how to escape dependency hell and make this work with KC 23.0.0 version? I've tried to get it working to no avail, at this point I am even willing to leave the java-configuration module aside, just to get the KC part at least back running. 

Any hint would be greatly appreciated!

**Comment by MaikKingma** [comment]
Great to hear that you like the demos. We are planning to release a lot more how-to's in the next few weeks and months.
As for Keycloak 23.0.0, I tend to wait a few minor releases before tackling new major releases.
It will most definitely be a topic in the upcoming tutorials though! So stay tuned :-)

**Comment by MaikKingma** [comment]
Btw. I think I do have a fix for you. It is also part of my next blog post. It should be released somewhere next week. I will post the link here once it is released.

**Comment by MaikKingma** [comment]
Here is the code for upgrading to 23.0.1 for the config as code approach. Blog will follow :) https://github.com/MaikKingma/keycloak-configAsCode-demo/tree/Blog-6/upgrade-to-23-0-1

**Comment by MaikKingma** [comment]
> Thanks for replying! I did manage to get it working with 23.0.0 & 23.0.1 but I am looking forward to your blog posts regardless 👍🏼

Nicely done! Good to hear.
