### ISSUE TITLE
links to the blogs in the README.md file are not valid

### ISSUE THREAD

**Issue by entero-somero-elso** [MaikKingma/keycloak-configAsCode-demo#5]
Hi, came here from the devoxx talk, noticed the links in the README.md file point to [blog.the-experts.nl](https://blog.the-experts.nl/) but should point to the new website: [tech-talk.the-experts.nl](https://tech-talk.the-experts.nl) where the blog posts are accesible.

**Comment by MaikKingma** [comment]
Thanks for pointing that out. We will update this ASAP
